#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_LiufangzheCommon

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "KuroAnim_structs.hpp"
#include "ELiufangzheWeaponType_structs.hpp"
#include "ABP_MonsterCommon_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_LiufangzheCommon.ABP_LiufangzheCommon_C
// 0x5600 (0x9B00 - 0x4500)
class UABP_LiufangzheCommon_C : public UABP_MonsterCommon_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ABP_LiufangzheCommon_C;             // 0x4500(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_1_ABP_LiufangzheCommon_C;       // 0x4508(0x0038)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C; // 0x4540(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C; // 0x4560(0x0020)()
	struct FAnimNode_Feedback                     AnimGraphNode_Feedback_ABP_LiufangzheCommon_C;     // 0x4580(0x0260)()
	struct FAnimNode_SightLock                    AnimGraphNode_SightLock_ABP_LiufangzheCommon_C;    // 0x47E0(0x01B8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C; // 0x4998(0x0138)()
	struct FAnimNode_BoneRotateToLocation         AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C; // 0x4AD0(0x0120)()
	struct FAnimNode_Root                         AnimGraphNode_Root_ABP_LiufangzheCommon_C;         // 0x4BF0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44_ABP_LiufangzheCommon_C; // 0x4C28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43_ABP_LiufangzheCommon_C; // 0x4C50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42_ABP_LiufangzheCommon_C; // 0x4C78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41_ABP_LiufangzheCommon_C; // 0x4CA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40_ABP_LiufangzheCommon_C; // 0x4CC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39_ABP_LiufangzheCommon_C; // 0x4CF0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x4D18(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22_ABP_LiufangzheCommon_C; // 0x4D48(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_67;                   // 0x4D80(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_66;                   // 0x4E10(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_65;                   // 0x4EA0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_64;                   // 0x4F30(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_63;                   // 0x4FC0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_62;                   // 0x5050(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_7;                    // 0x50E0(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21_ABP_LiufangzheCommon_C; // 0x5190(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C; // 0x51C8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20_ABP_LiufangzheCommon_C; // 0x51F8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x5230(0x0148)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38_ABP_LiufangzheCommon_C; // 0x5378(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37_ABP_LiufangzheCommon_C; // 0x53A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36_ABP_LiufangzheCommon_C; // 0x53C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35_ABP_LiufangzheCommon_C; // 0x53F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34_ABP_LiufangzheCommon_C; // 0x5418(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33_ABP_LiufangzheCommon_C; // 0x5440(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32_ABP_LiufangzheCommon_C; // 0x5468(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31_ABP_LiufangzheCommon_C; // 0x5490(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30_ABP_LiufangzheCommon_C; // 0x54B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29_ABP_LiufangzheCommon_C; // 0x54E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28_ABP_LiufangzheCommon_C; // 0x5508(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_61;                   // 0x5530(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_60;                   // 0x55C0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_59;                   // 0x5650(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_58;                   // 0x56E0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_57;                   // 0x5770(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_56;                   // 0x5800(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_6;                    // 0x5890(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19_ABP_LiufangzheCommon_C; // 0x5940(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_55;                   // 0x5978(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_54;                   // 0x5A08(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_53;                   // 0x5A98(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_52;                   // 0x5B28(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_51;                   // 0x5BB8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_50;                   // 0x5C48(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_5;                    // 0x5CD8(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18_ABP_LiufangzheCommon_C; // 0x5D88(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_49;                   // 0x5DC0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_48;                   // 0x5E50(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_47;                   // 0x5EE0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_46;                   // 0x5F70(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_45;                   // 0x6000(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_44;                   // 0x6090(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_4;                    // 0x6120(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17_ABP_LiufangzheCommon_C; // 0x61D0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_43;                   // 0x6208(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_42;                   // 0x6298(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_41;                   // 0x6328(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_40;                   // 0x63B8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_39;                   // 0x6448(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_38;                   // 0x64D8(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_3;                    // 0x6568(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16_ABP_LiufangzheCommon_C; // 0x6618(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C; // 0x6650(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15_ABP_LiufangzheCommon_C; // 0x6680(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C; // 0x66B8(0x0148)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x6800(0x01B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C; // 0x69B0(0x01B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27_ABP_LiufangzheCommon_C; // 0x6B60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C; // 0x6B88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C; // 0x6BB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C; // 0x6BD8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C; // 0x6C00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C; // 0x6C28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C; // 0x6C50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C; // 0x6C78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C; // 0x6CA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C; // 0x6CC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C; // 0x6CF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C; // 0x6D18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C; // 0x6D40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C; // 0x6D68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C; // 0x6D90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C; // 0x6DB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C; // 0x6DE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C; // 0x6E08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C; // 0x6E30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C; // 0x6E58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C; // 0x6E80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C; // 0x6EA8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_37_ABP_LiufangzheCommon_C; // 0x6ED0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_36_ABP_LiufangzheCommon_C; // 0x6F60(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_35_ABP_LiufangzheCommon_C; // 0x6FF0(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_3_ABP_LiufangzheCommon_C; // 0x7080(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C; // 0x7140(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C; // 0x7178(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C; // 0x71A0(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C; // 0x71D8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34_ABP_LiufangzheCommon_C; // 0x7210(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C; // 0x72A0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33_ABP_LiufangzheCommon_C; // 0x72D8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C; // 0x7368(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32_ABP_LiufangzheCommon_C; // 0x73A0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31_ABP_LiufangzheCommon_C; // 0x7430(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30_ABP_LiufangzheCommon_C; // 0x74C0(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_2_ABP_LiufangzheCommon_C; // 0x7550(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C; // 0x7610(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29_ABP_LiufangzheCommon_C; // 0x7648(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28_ABP_LiufangzheCommon_C; // 0x76D8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27_ABP_LiufangzheCommon_C; // 0x7768(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1_ABP_LiufangzheCommon_C; // 0x77F8(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C; // 0x78B8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C; // 0x78F0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26_ABP_LiufangzheCommon_C; // 0x7918(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25_ABP_LiufangzheCommon_C; // 0x79A8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24_ABP_LiufangzheCommon_C; // 0x7A38(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23_ABP_LiufangzheCommon_C; // 0x7AC8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22_ABP_LiufangzheCommon_C; // 0x7B58(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21_ABP_LiufangzheCommon_C; // 0x7BE8(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_ABP_LiufangzheCommon_C; // 0x7C78(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C; // 0x7D38(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C; // 0x7D70(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C; // 0x7DA0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C; // 0x7DD8(0x0148)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20_ABP_LiufangzheCommon_C; // 0x7F20(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19_ABP_LiufangzheCommon_C; // 0x7FB0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18_ABP_LiufangzheCommon_C; // 0x8040(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17_ABP_LiufangzheCommon_C; // 0x80D0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16_ABP_LiufangzheCommon_C; // 0x8160(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15_ABP_LiufangzheCommon_C; // 0x81F0(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_2;                    // 0x8280(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C; // 0x8330(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14_ABP_LiufangzheCommon_C; // 0x8368(0x0090)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x83F8(0x00D0)()
	struct FAnimNode_MakeDynamicAdditive          AnimGraphNode_MakeDynamicAdditive;                 // 0x84C8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13_ABP_LiufangzheCommon_C; // 0x8500(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12_ABP_LiufangzheCommon_C; // 0x8590(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11_ABP_LiufangzheCommon_C; // 0x8620(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C; // 0x86B0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C; // 0x8740(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C; // 0x87D0(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_1;                    // 0x8860(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C; // 0x8910(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C; // 0x8948(0x0148)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C; // 0x8A90(0x01B0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C;       // 0x8C40(0x0060)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C; // 0x8CA0(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C;       // 0x8D60(0x0060)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C; // 0x8DC0(0x01B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C; // 0x8F70(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C; // 0x8F98(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_ABP_LiufangzheCommon_C;         // 0x8FC0(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C; // 0x9020(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C; // 0x90B0(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C; // 0x90E8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C; // 0x9118(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C; // 0x9150(0x0148)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C; // 0x9298(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C; // 0x92C0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C; // 0x92E8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C; // 0x9378(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C; // 0x9408(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C; // 0x9498(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C; // 0x9528(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C; // 0x95B8(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x9648(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C; // 0x96F8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C; // 0x9730(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_ABP_LiufangzheCommon_C;  // 0x97C0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C; // 0x97F8(0x0148)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C; // 0x9940(0x01B0)()
	bool                                          ___0;                                              // 0x9AF0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          _kh_0;                                             // 0x9AF1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          _0;                                                // 0x9AF2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Five__0;                                           // 0x9AF3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ____0;                                             // 0x9AF4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	ELiufangzheWeaponType                         Fh__;                                              // 0x9AF5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          A__7;                                              // 0x9AF6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          A__s;                                              // 0x9AF7(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_LiufangzheCommon(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_52C450844EBF9BFBB8282B9C6B941D1D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_C823D0574DC7BFFD1486B185FB74217D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8E52222C4F7CCA4D8A2BD6955D653104();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_0E3C99E146C38005332675958239B31D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_78BE75ED4C9F1548F6881EA7C9ABF4E3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_6684FE9C458CA18198F2F6869D5F50BC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_6D4A355648553BA8DC9ED5BBD4A5BE4F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_D0E8C1B244BA4AE4F53BDAAB951909F1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8D24B3C84F11D4FB693B7D8E2C17750E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_D7E7038741792DF8F4A08D844645A02B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_0E45F0A248B5EB834B1D118F89243BA4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_51ACED6F4934CF7F238A3D96E5032A90();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_AE5AEE88411D7A64F1658EB02757165D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_4AC22FD044DE03780A4E2EA42024E95D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_ED42731540984E9B5E52E295CD3D3AFD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_DD3D8D8B4A0C9E8BF8CB268A990B6AB7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_038BD5884F253D75CC75A7B7E01FF7D1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_C94ECA934CA1B69A6B96AFA2CCEDA69E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_734160404187CF651CD4A58A68954FC3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_73A9AE2F422C05AD32CD6E89F9D8FC5D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_E17D8B5545F0B8950DC1E685D29CA41E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_44F768BE4EF62984DC660CA208794E4C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8BCEBEFD4E80ABEED11F33AEBBE8E07A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_B859894D4196260BB9D990B58667D389();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_91D6953F49819543EB80E18778493B28();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_5698CF474CA398956D5F57A24D8EAF21();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_2E6E0A0341F76826D3A50B9B86F40869();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_27B9F7744E79632838E7D493A59E1DF8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_653B74A24B3267FB601126A104B583E0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_166E975E48E756AB32647B922F7B4BAF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_C9529B2F4415C6A3301735A1EAD298B6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_FB6C909D404D38CD70FD1DA55BF02B92();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_E285C5B644D0C7EDEB0867BB1A35D376();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_2A58B9C64010468AE65A28A34150184F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_0165AE4B44D6CA5FC416FEA0ABD19225();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_C904936E4A91604CE61911B883E94EAD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_79A63DAC4F1506CACEC0A5829047958E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_Feedback_1110F51F47BAC0E6EDD68BB579A50C8A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BoneRotateToLocation_1980760A423198CC6ADEF49705FC9B54();
	void ______Tag();
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void IKAndFk_Clone(const struct FPoseLink& InPose, struct FPoseLink* Param_IKAndFk_Clone);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_LiufangzheCommon_C">();
	}
	static class UABP_LiufangzheCommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_LiufangzheCommon_C>();
	}
};
static_assert(alignof(UABP_LiufangzheCommon_C) == 0x000010, "Wrong alignment on UABP_LiufangzheCommon_C");
static_assert(sizeof(UABP_LiufangzheCommon_C) == 0x009B00, "Wrong size on UABP_LiufangzheCommon_C");
static_assert(offsetof(UABP_LiufangzheCommon_C, UberGraphFrame_ABP_LiufangzheCommon_C) == 0x004500, "Member 'UABP_LiufangzheCommon_C::UberGraphFrame_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Root_1_ABP_LiufangzheCommon_C) == 0x004508, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Root_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C) == 0x004540, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C) == 0x004560, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Feedback_ABP_LiufangzheCommon_C) == 0x004580, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Feedback_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SightLock_ABP_LiufangzheCommon_C) == 0x0047E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SightLock_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C) == 0x004998, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C) == 0x004AD0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Root_ABP_LiufangzheCommon_C) == 0x004BF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Root_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_44_ABP_LiufangzheCommon_C) == 0x004C28, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_44_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_43_ABP_LiufangzheCommon_C) == 0x004C50, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_43_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_42_ABP_LiufangzheCommon_C) == 0x004C78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_42_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_41_ABP_LiufangzheCommon_C) == 0x004CA0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_41_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_40_ABP_LiufangzheCommon_C) == 0x004CC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_40_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_39_ABP_LiufangzheCommon_C) == 0x004CF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_39_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_4) == 0x004D18, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_22_ABP_LiufangzheCommon_C) == 0x004D48, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_22_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_67) == 0x004D80, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_67' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_66) == 0x004E10, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_66' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_65) == 0x004EA0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_65' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_64) == 0x004F30, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_64' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_63) == 0x004FC0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_63' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_62) == 0x005050, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_62' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_7) == 0x0050E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_7' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_21_ABP_LiufangzheCommon_C) == 0x005190, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_21_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C) == 0x0051C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_20_ABP_LiufangzheCommon_C) == 0x0051F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_20_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_5) == 0x005230, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_38_ABP_LiufangzheCommon_C) == 0x005378, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_38_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_37_ABP_LiufangzheCommon_C) == 0x0053A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_37_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_36_ABP_LiufangzheCommon_C) == 0x0053C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_36_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_35_ABP_LiufangzheCommon_C) == 0x0053F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_35_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_34_ABP_LiufangzheCommon_C) == 0x005418, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_34_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_33_ABP_LiufangzheCommon_C) == 0x005440, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_33_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_32_ABP_LiufangzheCommon_C) == 0x005468, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_32_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_31_ABP_LiufangzheCommon_C) == 0x005490, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_31_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_30_ABP_LiufangzheCommon_C) == 0x0054B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_30_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_29_ABP_LiufangzheCommon_C) == 0x0054E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_29_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_28_ABP_LiufangzheCommon_C) == 0x005508, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_28_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_61) == 0x005530, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_61' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_60) == 0x0055C0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_60' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_59) == 0x005650, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_59' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_58) == 0x0056E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_58' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_57) == 0x005770, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_57' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_56) == 0x005800, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_56' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_6) == 0x005890, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_6' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_19_ABP_LiufangzheCommon_C) == 0x005940, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_19_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_55) == 0x005978, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_55' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_54) == 0x005A08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_54' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_53) == 0x005A98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_53' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_52) == 0x005B28, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_52' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_51) == 0x005BB8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_51' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_50) == 0x005C48, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_50' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_5) == 0x005CD8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_5' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_18_ABP_LiufangzheCommon_C) == 0x005D88, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_18_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_49) == 0x005DC0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_49' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_48) == 0x005E50, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_48' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_47) == 0x005EE0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_47' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_46) == 0x005F70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_46' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_45) == 0x006000, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_45' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_44) == 0x006090, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_44' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_4) == 0x006120, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_17_ABP_LiufangzheCommon_C) == 0x0061D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_17_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_43) == 0x006208, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_43' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_42) == 0x006298, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_42' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_41) == 0x006328, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_41' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_40) == 0x0063B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_40' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_39) == 0x006448, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_39' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_38) == 0x0064D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_38' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_3) == 0x006568, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_3' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_16_ABP_LiufangzheCommon_C) == 0x006618, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_16_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C) == 0x006650, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_15_ABP_LiufangzheCommon_C) == 0x006680, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_15_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C) == 0x0066B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_4) == 0x006800, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C) == 0x0069B0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_27_ABP_LiufangzheCommon_C) == 0x006B60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_27_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C) == 0x006B88, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C) == 0x006BB0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C) == 0x006BD8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C) == 0x006C00, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C) == 0x006C28, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C) == 0x006C50, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C) == 0x006C78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C) == 0x006CA0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C) == 0x006CC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C) == 0x006CF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C) == 0x006D18, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C) == 0x006D40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C) == 0x006D68, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C) == 0x006D90, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C) == 0x006DB8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C) == 0x006DE0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C) == 0x006E08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C) == 0x006E30, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C) == 0x006E58, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C) == 0x006E80, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C) == 0x006EA8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_37_ABP_LiufangzheCommon_C) == 0x006ED0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_37_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_36_ABP_LiufangzheCommon_C) == 0x006F60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_36_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_35_ABP_LiufangzheCommon_C) == 0x006FF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_35_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_3_ABP_LiufangzheCommon_C) == 0x007080, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C) == 0x007140, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C) == 0x007178, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C) == 0x0071A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C) == 0x0071D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_34_ABP_LiufangzheCommon_C) == 0x007210, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_34_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C) == 0x0072A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_33_ABP_LiufangzheCommon_C) == 0x0072D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_33_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C) == 0x007368, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_32_ABP_LiufangzheCommon_C) == 0x0073A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_32_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_31_ABP_LiufangzheCommon_C) == 0x007430, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_31_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_30_ABP_LiufangzheCommon_C) == 0x0074C0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_30_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_2_ABP_LiufangzheCommon_C) == 0x007550, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C) == 0x007610, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_29_ABP_LiufangzheCommon_C) == 0x007648, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_29_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_28_ABP_LiufangzheCommon_C) == 0x0076D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_28_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_27_ABP_LiufangzheCommon_C) == 0x007768, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_27_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_1_ABP_LiufangzheCommon_C) == 0x0077F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C) == 0x0078B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C) == 0x0078F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_26_ABP_LiufangzheCommon_C) == 0x007918, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_26_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_25_ABP_LiufangzheCommon_C) == 0x0079A8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_25_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_24_ABP_LiufangzheCommon_C) == 0x007A38, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_24_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_23_ABP_LiufangzheCommon_C) == 0x007AC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_23_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_22_ABP_LiufangzheCommon_C) == 0x007B58, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_22_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_21_ABP_LiufangzheCommon_C) == 0x007BE8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_21_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_ABP_LiufangzheCommon_C) == 0x007C78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C) == 0x007D38, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C) == 0x007D70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C) == 0x007DA0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C) == 0x007DD8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_20_ABP_LiufangzheCommon_C) == 0x007F20, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_20_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_19_ABP_LiufangzheCommon_C) == 0x007FB0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_19_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_18_ABP_LiufangzheCommon_C) == 0x008040, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_18_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_17_ABP_LiufangzheCommon_C) == 0x0080D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_17_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_16_ABP_LiufangzheCommon_C) == 0x008160, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_16_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_15_ABP_LiufangzheCommon_C) == 0x0081F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_15_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_2) == 0x008280, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_2' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C) == 0x008330, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_14_ABP_LiufangzheCommon_C) == 0x008368, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_14_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_ApplyAdditive) == 0x0083F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_MakeDynamicAdditive) == 0x0084C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_MakeDynamicAdditive' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_13_ABP_LiufangzheCommon_C) == 0x008500, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_13_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_12_ABP_LiufangzheCommon_C) == 0x008590, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_12_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_11_ABP_LiufangzheCommon_C) == 0x008620, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_11_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C) == 0x0086B0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C) == 0x008740, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C) == 0x0087D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_1) == 0x008860, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_1' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C) == 0x008910, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C) == 0x008948, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C) == 0x008A90, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C) == 0x008C40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C) == 0x008CA0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C) == 0x008D60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C) == 0x008DC0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C) == 0x008F70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C) == 0x008F98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_ABP_LiufangzheCommon_C) == 0x008FC0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C) == 0x009020, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C) == 0x0090B0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C) == 0x0090E8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C) == 0x009118, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C) == 0x009150, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C) == 0x009298, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C) == 0x0092C0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C) == 0x0092E8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C) == 0x009378, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C) == 0x009408, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C) == 0x009498, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C) == 0x009528, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C) == 0x0095B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt) == 0x009648, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C) == 0x0096F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C) == 0x009730, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_ABP_LiufangzheCommon_C) == 0x0097C0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C) == 0x0097F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C) == 0x009940, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, ___0) == 0x009AF0, "Member 'UABP_LiufangzheCommon_C::___0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, _kh_0) == 0x009AF1, "Member 'UABP_LiufangzheCommon_C::_kh_0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, _0) == 0x009AF2, "Member 'UABP_LiufangzheCommon_C::_0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, Five__0) == 0x009AF3, "Member 'UABP_LiufangzheCommon_C::Five__0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, ____0) == 0x009AF4, "Member 'UABP_LiufangzheCommon_C::____0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, Fh__) == 0x009AF5, "Member 'UABP_LiufangzheCommon_C::Fh__' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, A__7) == 0x009AF6, "Member 'UABP_LiufangzheCommon_C::A__7' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, A__s) == 0x009AF7, "Member 'UABP_LiufangzheCommon_C::A__s' has a wrong offset!");

}

