#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MO1ShouhuMd00002

#include "Basic.hpp"

#include "ABP_MO1ShouhuMd00002_classes.hpp"
#include "ABP_MO1ShouhuMd00002_parameters.hpp"


namespace SDK
{

// Function ABP_MO1ShouhuMd00002.ABP_MO1ShouhuMd00002_C.ExecuteUbergraph_ABP_MO1ShouhuMd00002
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_MO1ShouhuMd00002_C::ExecuteUbergraph_ABP_MO1ShouhuMd00002(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MO1ShouhuMd00002_C", "ExecuteUbergraph_ABP_MO1ShouhuMd00002");

	Params::ABP_MO1ShouhuMd00002_C_ExecuteUbergraph_ABP_MO1ShouhuMd00002 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_MO1ShouhuMd00002.ABP_MO1ShouhuMd00002_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_MO1ShouhuMd00002_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MO1ShouhuMd00002_C", "AnimGraph");

	Params::ABP_MO1ShouhuMd00002_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

