#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SwordScabbarcdCommon

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "EWeaponViewName_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_SwordScabbarcdCommon.ABP_SwordScabbarcdCommon_C
// 0x1750 (0x1AD0 - 0x0380)
class UABP_SwordScabbarcdCommon_C final : public UAnimInstance
{
public:
	uint8                                         Pad_378[0x8];                                      // 0x0378(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0388(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x03C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x03E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x0410(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x0438(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x0460(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x0488(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x04B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x04D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x0500(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x0528(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x0550(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x0578(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x05A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x05C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x05F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x0618(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x0640(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x0668(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x0690(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x06B8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x0748(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0780(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x0810(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0848(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x08D8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0910(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x09A0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x09D8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x0A68(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x0AA0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x0AD8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x0B68(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x0BA0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x0C30(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x0C68(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x0CF8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x0D30(0x0148)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x0E78(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x0EB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x0ED8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x0F00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x0F28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x0F50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x0F78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x0FA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x0FC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x0FF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x1018(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x1040(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x1068(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x1090(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x10B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x10E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x1108(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x1130(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1158(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x11E8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1220(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x12B0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x12E8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1378(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x13B0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1440(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1478(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1508(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x1540(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x1578(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1608(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x1640(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x16D0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x1708(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x1798(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x17D0(0x0148)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1918(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x1950(0x0148)()
	class ATsBaseCharacter_C*                     _r__;                                              // 0x1A98(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WeaponOpen;                                        // 0x1AA0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1AA1[0x3];                                     // 0x1AA1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Open_Delay;                                        // 0x1AA4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta_Time;                                        // 0x1AA8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __s_fh;                                            // 0x1AAC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Fh___;                                             // 0x1AAD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Weapon_Open;                                       // 0x1AAE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsUI;                                              // 0x1AAF(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	int32                                         Fh_4I_;                                            // 0x1AB0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SMfh_4I_;                                          // 0x1AB4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsUiSceneRoleActor_C*                  UILb__;                                            // 0x1AB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EWeaponViewName                               UILb;                                              // 0x1AC0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          _c_____yH;                                         // 0x1AC1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_SwordScabbarcdCommon(int32 EntryPoint);
	void Set_Open_Delay();
	void Clear_Open_Delay();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0B83C93C4704BD56331EC790C125D684();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_60E48CAF40555926DE89C683DAB10735();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BB2EB9A94C64021CEE07D9890242972D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BA0F8FE8454D662D6D3A159E338D4192();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_5E35E85944D11EB2E66E959A3D1B7736();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_E060EB0545B3DC9906CF0988CB31CA5E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_C5D9C39D47564CFCA30F48848C801924();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_3B14DCD949F0D28682EEF3AF215B7C88();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0C8605904D1B20A921689987444DA0D0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_22251D08423281B2C96078BA3493D5F8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_28958A5646EAA30D586DA2A3B2219E96();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_1D0051744B301420431041B80A871603();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_B656CD4C48A0FB2CD708C4B641023232();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_861469E64CA68F604289A29F52957779();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BF44640D412106701BE7818C40EC8836();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_4DC7BAB44412E7F9CB0FBB86EC77561E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_CE8439D84D1DBE11E2AF99944D23858E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_3C4EAFD6401882863A283AA35F8C0836();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_F1566B304355AC27F7B22FA8C6FE2660();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_EC01249D4172D395D5B8BDA0ABB12C8E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_5564B3AC47DA0EDCCAF082847FD13B53();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0359E2234EBDBEF31CCEB0970132CFA1();
	void AnimGraph(struct FPoseLink* Param_AnimGraph);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_SwordScabbarcdCommon_C">();
	}
	static class UABP_SwordScabbarcdCommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_SwordScabbarcdCommon_C>();
	}
};
static_assert(alignof(UABP_SwordScabbarcdCommon_C) == 0x000010, "Wrong alignment on UABP_SwordScabbarcdCommon_C");
static_assert(sizeof(UABP_SwordScabbarcdCommon_C) == 0x001AD0, "Wrong size on UABP_SwordScabbarcdCommon_C");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, UberGraphFrame) == 0x000380, "Member 'UABP_SwordScabbarcdCommon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_Root) == 0x000388, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_35) == 0x0003C0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_34) == 0x0003E8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_33) == 0x000410, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_32) == 0x000438, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_31) == 0x000460, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_30) == 0x000488, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_29) == 0x0004B0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_28) == 0x0004D8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_27) == 0x000500, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_26) == 0x000528, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_25) == 0x000550, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_24) == 0x000578, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_23) == 0x0005A0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_22) == 0x0005C8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_21) == 0x0005F0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_20) == 0x000618, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_19) == 0x000640, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_18) == 0x000668, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_17) == 0x000690, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_15) == 0x0006B8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_19) == 0x000748, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_14) == 0x000780, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_18) == 0x000810, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_13) == 0x000848, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_17) == 0x0008D8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_12) == 0x000910, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_16) == 0x0009A0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_11) == 0x0009D8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_15) == 0x000A68, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_14) == 0x000AA0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_10) == 0x000AD8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_13) == 0x000B68, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_9) == 0x000BA0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_12) == 0x000C30, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_8) == 0x000C68, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_11) == 0x000CF8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateMachine_2) == 0x000D30, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_10) == 0x000E78, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_16) == 0x000EB0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_15) == 0x000ED8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_14) == 0x000F00, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_13) == 0x000F28, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_12) == 0x000F50, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_11) == 0x000F78, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_10) == 0x000FA0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_9) == 0x000FC8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_8) == 0x000FF0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_7) == 0x001018, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_6) == 0x001040, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_5) == 0x001068, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_4) == 0x001090, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_3) == 0x0010B8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_2) == 0x0010E0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult_1) == 0x001108, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_TransitionResult) == 0x001130, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_7) == 0x001158, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_9) == 0x0011E8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_6) == 0x001220, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_8) == 0x0012B0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_5) == 0x0012E8, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_7) == 0x001378, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_4) == 0x0013B0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_6) == 0x001440, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_3) == 0x001478, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_5) == 0x001508, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_4) == 0x001540, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_2) == 0x001578, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_3) == 0x001608, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer_1) == 0x001640, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_2) == 0x0016D0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_SequencePlayer) == 0x001708, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult_1) == 0x001798, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateMachine_1) == 0x0017D0, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateResult) == 0x001918, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, AnimGraphNode_StateMachine) == 0x001950, "Member 'UABP_SwordScabbarcdCommon_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, _r__) == 0x001A98, "Member 'UABP_SwordScabbarcdCommon_C::_r__' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, WeaponOpen) == 0x001AA0, "Member 'UABP_SwordScabbarcdCommon_C::WeaponOpen' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, Open_Delay) == 0x001AA4, "Member 'UABP_SwordScabbarcdCommon_C::Open_Delay' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, Delta_Time) == 0x001AA8, "Member 'UABP_SwordScabbarcdCommon_C::Delta_Time' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, __s_fh) == 0x001AAC, "Member 'UABP_SwordScabbarcdCommon_C::__s_fh' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, Fh___) == 0x001AAD, "Member 'UABP_SwordScabbarcdCommon_C::Fh___' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, Weapon_Open) == 0x001AAE, "Member 'UABP_SwordScabbarcdCommon_C::Weapon_Open' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, IsUI) == 0x001AAF, "Member 'UABP_SwordScabbarcdCommon_C::IsUI' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, Fh_4I_) == 0x001AB0, "Member 'UABP_SwordScabbarcdCommon_C::Fh_4I_' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, SMfh_4I_) == 0x001AB4, "Member 'UABP_SwordScabbarcdCommon_C::SMfh_4I_' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, UILb__) == 0x001AB8, "Member 'UABP_SwordScabbarcdCommon_C::UILb__' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, UILb) == 0x001AC0, "Member 'UABP_SwordScabbarcdCommon_C::UILb' has a wrong offset!");
static_assert(offsetof(UABP_SwordScabbarcdCommon_C, _c_____yH) == 0x001AC1, "Member 'UABP_SwordScabbarcdCommon_C::_c_____yH' has a wrong offset!");

}

