#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_ELingyangLionHeadMd10011_PC

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "KawaiiPhysics_structs.hpp"
#include "BPE_LionHeadAction_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_ELingyangLionHeadMd10011_PC.ABP_ELingyangLionHeadMd10011_PC_C
// 0x23D0 (0x2750 - 0x0380)
class UABP_ELingyangLionHeadMd10011_PC_C final : public UAnimInstance
{
public:
	uint8                                         Pad_378[0x8];                                      // 0x0378(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0388(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x03A8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x03C8(0x0138)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_2;                // 0x0500(0x0270)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_1;                // 0x0770(0x0270)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup;                  // 0x09E0(0x0270)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0C50(0x0038)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x0C88(0x00C0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0D48(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x0D80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x0DA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x0DD0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x0DF8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x0E20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x0E48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x0E70(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x0E98(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x0EC0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x0EE8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x0F10(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x0F38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x0F60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x0F88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x0FB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x0FD8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x1000(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x1028(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x1050(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x1078(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x10A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x10C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x10F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x1118(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x1140(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x1168(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x1190(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x11B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x11E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x1208(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x1230(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1258(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x1280(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x12A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x12D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x12F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x1320(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x1348(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x1370(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x1400(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x1438(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x14C8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x1500(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x1590(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x15C8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x1658(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x1690(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x1720(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x1758(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x17E8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x1820(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x18B0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x18E8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x1978(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x19B0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x1A40(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x1A78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x1AA0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x1AC8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x1B58(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1B90(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x1C20(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1C58(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x1CE8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x1D20(0x0148)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x1E68(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1EA0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x1F30(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1F68(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1FF8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x2030(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x20C0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x20F8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x2188(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x21C0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x2250(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x2288(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x2318(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x2350(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x23E0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x2418(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x2440(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x24D0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x2508(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x2598(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x25D0(0x0148)()
	class ATsBaseCharacter_C*                     _r__;                                              // 0x2718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          _4__;                                              // 0x2720(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2721[0x7];                                     // 0x2721(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimaryDataAsset*                      HideEffect;                                        // 0x2728(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          AnimInstance;                                      // 0x2730(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 LionHead;                                          // 0x2738(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBPE_LionHeadAction                           LionHeadAction;                                    // 0x2740(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          _AIRMOVE01;                                        // 0x2741(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsFirst;                                           // 0x2742(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_25F4EFEC452ECE12D17170B490FD4DB0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_47F5C13B41F0F13E495DB6BD0A508F16();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_EF2368AA4897ADB4AFAA0B92610EDBBB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_C95921F3455716A4D496D491EF09DCEA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_00CC626A45EC241939DD66BED6271782();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_99570C8742AF318FAACC119E858559EB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_FA7D5E654661DD6F49BC8DBD7F45F86C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_F68A23AE4D175FECAD22EB9D621325F9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_872667494C8CA07F6BAB73A972753AFD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_2141406840C8BEB758886D98F4D6BB36();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_3C475D804A2A2CCBA78C749BB7C68449();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_4AE346654D15108FE85926B78A283173();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_1E667E0C4641A63213ECE39AC6784814();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_A87DA0BE40D702FB6824DC8452EAEC96();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_58A1CB454DF0AC5891A3208AF99DF82B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_4ACF67C94C0F4D9CCF9A46A6B2429B33();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_DE1802C848CA7DFF9017F8B60EE34382();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_BD54D2FD45523C4C2BC974A6EC09892B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_A4B44DE44768566E0F332F9762DBD734();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_9E9E17634CC468BFE0540F8C0FAAA922();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_647B7D54447A4810DD814EAE53849BE9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_8940DADF4AE76FD6C77C4896F59AF94E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_D52EBA624B3B9E3A37E4FA84FC81A6AF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_68111C114361780309E8EBAEE9863270();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_77FDE1674D763C83B8A4E29C75711047();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_E193475B46E168DD96BA27AC9EB94969();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_5DC2C5114CF38360E68F8FA28643690D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_791A949242ABEF4FB79251A24E9B22CD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_4F23F0674CFE0DF19A0DE08D0374DA03();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_2A26C4E5494424AE0E2449B664962434();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_378E1D4B47E3C3FAD651039F38120CCA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_98BCFEE548719BC2A8A53F86C4C3664F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_F126D5724BA0D3310ADB1A95578C0076();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_731CB8E94338C3BE1A5461A6434A5845();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_DBF5CC2A4F7BC10488691DB593FE0C94();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_2FE34E5743D69F66CE4A6FAA13913FC7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_6921A3F74A4D59D129FBF9B576295BEB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_4E610A424848D8F57D7A4DBEDA374566();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_C9CAB202435CB42F90DC09A112C6AF96();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_ELingyangLionHeadMd10011_PC_AnimGraphNode_TransitionResult_ABFA3441400402C39F61D68F90D4F6B3();
	void ___();
	void ___4____();
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void PhyCloth(const struct FPoseLink& InPose, struct FPoseLink* Param_PhyCloth);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_ELingyangLionHeadMd10011_PC_C">();
	}
	static class UABP_ELingyangLionHeadMd10011_PC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_ELingyangLionHeadMd10011_PC_C>();
	}
};
static_assert(alignof(UABP_ELingyangLionHeadMd10011_PC_C) == 0x000010, "Wrong alignment on UABP_ELingyangLionHeadMd10011_PC_C");
static_assert(sizeof(UABP_ELingyangLionHeadMd10011_PC_C) == 0x002750, "Wrong size on UABP_ELingyangLionHeadMd10011_PC_C");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, UberGraphFrame) == 0x000380, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_LocalToComponentSpace) == 0x000388, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_ComponentToLocalSpace) == 0x0003A8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_LinkedInputPose) == 0x0003C8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_2) == 0x000500, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_2' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_1) == 0x000770, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup) == 0x0009E0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_Root_1) == 0x000C50, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_LinkedAnimLayer) == 0x000C88, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_Root) == 0x000D48, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_40) == 0x000D80, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_40' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_39) == 0x000DA8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_39' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_38) == 0x000DD0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_38' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_37) == 0x000DF8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_37' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_36) == 0x000E20, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_36' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_35) == 0x000E48, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_34) == 0x000E70, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_33) == 0x000E98, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_32) == 0x000EC0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_31) == 0x000EE8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_30) == 0x000F10, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_29) == 0x000F38, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_28) == 0x000F60, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_27) == 0x000F88, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_26) == 0x000FB0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_25) == 0x000FD8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_24) == 0x001000, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_23) == 0x001028, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_22) == 0x001050, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_21) == 0x001078, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_20) == 0x0010A0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_19) == 0x0010C8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_18) == 0x0010F0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_17) == 0x001118, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_16) == 0x001140, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_15) == 0x001168, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_14) == 0x001190, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_13) == 0x0011B8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_12) == 0x0011E0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_11) == 0x001208, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_10) == 0x001230, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_9) == 0x001258, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_8) == 0x001280, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_7) == 0x0012A8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_6) == 0x0012D0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_5) == 0x0012F8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_4) == 0x001320, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_3) == 0x001348, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_20) == 0x001370, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_21) == 0x001400, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_19) == 0x001438, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_20) == 0x0014C8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_18) == 0x001500, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_19) == 0x001590, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_17) == 0x0015C8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_18) == 0x001658, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_16) == 0x001690, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_17) == 0x001720, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_15) == 0x001758, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_16) == 0x0017E8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_14) == 0x001820, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_15) == 0x0018B0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_13) == 0x0018E8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_14) == 0x001978, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_12) == 0x0019B0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_13) == 0x001A40, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_2) == 0x001A78, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult_1) == 0x001AA0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_11) == 0x001AC8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_12) == 0x001B58, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_10) == 0x001B90, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_11) == 0x001C20, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_9) == 0x001C58, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_10) == 0x001CE8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateMachine_1) == 0x001D20, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_9) == 0x001E68, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_8) == 0x001EA0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_8) == 0x001F30, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_7) == 0x001F68, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_7) == 0x001FF8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_6) == 0x002030, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_6) == 0x0020C0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_5) == 0x0020F8, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_5) == 0x002188, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_4) == 0x0021C0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_4) == 0x002250, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_3) == 0x002288, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_3) == 0x002318, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_2) == 0x002350, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_2) == 0x0023E0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_TransitionResult) == 0x002418, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer_1) == 0x002440, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult_1) == 0x0024D0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_SequencePlayer) == 0x002508, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateResult) == 0x002598, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimGraphNode_StateMachine) == 0x0025D0, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, _r__) == 0x002718, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::_r__' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, _4__) == 0x002720, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::_4__' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, HideEffect) == 0x002728, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::HideEffect' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, AnimInstance) == 0x002730, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::AnimInstance' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, LionHead) == 0x002738, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::LionHead' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, LionHeadAction) == 0x002740, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::LionHeadAction' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, _AIRMOVE01) == 0x002741, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::_AIRMOVE01' has a wrong offset!");
static_assert(offsetof(UABP_ELingyangLionHeadMd10011_PC_C, IsFirst) == 0x002742, "Member 'UABP_ELingyangLionHeadMd10011_PC_C::IsFirst' has a wrong offset!");

}

