#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MO1ShouhuMd00002

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_MO1ShouhuMd00002.ABP_MO1ShouhuMd00002_C
// 0x0040 (0x03C0 - 0x0380)
class UABP_MO1ShouhuMd00002_C final : public UAnimInstance
{
public:
	uint8                                         Pad_378[0x8];                                      // 0x0378(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0388(0x0038)()

public:
	void ExecuteUbergraph_ABP_MO1ShouhuMd00002(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* Param_AnimGraph);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_MO1ShouhuMd00002_C">();
	}
	static class UABP_MO1ShouhuMd00002_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_MO1ShouhuMd00002_C>();
	}
};
static_assert(alignof(UABP_MO1ShouhuMd00002_C) == 0x000010, "Wrong alignment on UABP_MO1ShouhuMd00002_C");
static_assert(sizeof(UABP_MO1ShouhuMd00002_C) == 0x0003C0, "Wrong size on UABP_MO1ShouhuMd00002_C");
static_assert(offsetof(UABP_MO1ShouhuMd00002_C, UberGraphFrame) == 0x000380, "Member 'UABP_MO1ShouhuMd00002_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_MO1ShouhuMd00002_C, AnimGraphNode_Root) == 0x000388, "Member 'UABP_MO1ShouhuMd00002_C::AnimGraphNode_Root' has a wrong offset!");

}

