#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_AIMO1YouyidieMd00501

#include "Basic.hpp"

#include "AIC_AIMO1YouyidieMd00501_classes.hpp"
#include "AIC_AIMO1YouyidieMd00501_parameters.hpp"


namespace SDK
{

// Function AIC_AIMO1YouyidieMd00501.AIC_AIMO1YouyidieMd00501_C.ExecuteUbergraph_AIC_AIMO1YouyidieMd00501
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAIC_AIMO1YouyidieMd00501_C::ExecuteUbergraph_AIC_AIMO1YouyidieMd00501(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_AIMO1YouyidieMd00501_C", "ExecuteUbergraph_AIC_AIMO1YouyidieMd00501");

	Params::AIC_AIMO1YouyidieMd00501_C_ExecuteUbergraph_AIC_AIMO1YouyidieMd00501 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_AIMO1YouyidieMd00501.AIC_AIMO1YouyidieMd00501_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void AAIC_AIMO1YouyidieMd00501_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_AIMO1YouyidieMd00501_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIC_AIMO1YouyidieMd00501.AIC_AIMO1YouyidieMd00501_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAIC_AIMO1YouyidieMd00501_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_AIMO1YouyidieMd00501_C", "ReceiveTick");

	Params::AIC_AIMO1YouyidieMd00501_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

