#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_NA015

#include "Basic.hpp"

#include "AIC_NA015_classes.hpp"
#include "AIC_NA015_parameters.hpp"


namespace SDK
{

// Function AIC_NA015.AIC_NA015_C.ExecuteUbergraph_AIC_NA015
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAIC_NA015_C::ExecuteUbergraph_AIC_NA015(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_NA015_C", "ExecuteUbergraph_AIC_NA015");

	Params::AIC_NA015_C_ExecuteUbergraph_AIC_NA015 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_NA015.AIC_NA015_C.×û
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ATsBaseCharacter_C*               _r                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSHitInformation                 __pn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference, HasGetValueTypeHash)

void AAIC_NA015_C::__(class ATsBaseCharacter_C* _r, const struct FSHitInformation& __pn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_NA015_C", "×û");

	Params::AIC_NA015_C___ Parms{};

	Parms._r = _r;
	Parms.__pn = std::move(__pn);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIC_NA015.AIC_NA015_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void AAIC_NA015_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIC_NA015_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

