#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CommonPet

#include "Basic.hpp"

#include "BP_BaseAnimal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CommonPet.BP_CommonPet_C
// 0x0010 (0x0790 - 0x0780)
class ABP_CommonPet_C : public ABP_BaseAnimal_C
{
public:
	class UBoxComponent*                          BlurCollision;                                     // 0x0780(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CommonPet_C">();
	}
	static class ABP_CommonPet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CommonPet_C>();
	}
};
static_assert(alignof(ABP_CommonPet_C) == 0x000010, "Wrong alignment on ABP_CommonPet_C");
static_assert(sizeof(ABP_CommonPet_C) == 0x000790, "Wrong size on ABP_CommonPet_C");
static_assert(offsetof(ABP_CommonPet_C, BlurCollision) == 0x000780, "Member 'ABP_CommonPet_C::BlurCollision' has a wrong offset!");

}

