#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InputComponent_Baihu

#include "Basic.hpp"

#include "BP_InputComponent_Baihu_classes.hpp"
#include "BP_InputComponent_Baihu_parameters.hpp"


namespace SDK
{

// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.;û	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::Func______19(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", ";û	");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.€ý1	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::__1___0(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "€ý1	");

	Params::BP_InputComponent_Baihu_C___1__ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.;û	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::Func______18(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", ";û	");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.'Û	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::Func______17(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "'Û	");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.óÃ	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::Func______16(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "óÃ	");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.&áýÏ
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    __                                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_InputComponent_Baihu_C::Func______15(bool* __)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "&áýÏ");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (__ != nullptr)
		*__ = Parms.__;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.ê	
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_InputComponent_Baihu_C::Func______14(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "ê	");

	Params::BP_InputComponent_Baihu_C_____ Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.&zýÏ
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Z                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_InputComponent_Baihu_C::_z__(bool* Z)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "&zýÏ");

	Params::BP_InputComponent_Baihu_C__z__ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Z != nullptr)
		*Z = Parms.Z;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.ýÏ'Ž50%
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    EntryPoint                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_InputComponent_Baihu_C::____50_(bool* EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "ýÏ'Ž50%");

	Params::BP_InputComponent_Baihu_C_____50_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EntryPoint != nullptr)
		*EntryPoint = Parms.EntryPoint;
}


// Function BP_InputComponent_Baihu.BP_InputComponent_Baihu_C.ýÏ'Ž10%
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    __                                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_InputComponent_Baihu_C::____10_(bool* __)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InputComponent_Baihu_C", "ýÏ'Ž10%");

	Params::BP_InputComponent_Baihu_C_____10_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (__ != nullptr)
		*__ = Parms.__;
}

}

