#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPE_LionHeadAction

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum BPE_LionHeadAction.BPE_LionHeadAction
// NumValues: 0x0017
enum class EBPE_LionHeadAction : uint8
{
	NewEnumerator21                          = 0,
	NewEnumerator0                           = 1,
	NewEnumerator22                          = 2,
	NewEnumerator1                           = 3,
	NewEnumerator2                           = 4,
	NewEnumerator20                          = 5,
	NewEnumerator3                           = 6,
	NewEnumerator4                           = 7,
	NewEnumerator5                           = 8,
	NewEnumerator6                           = 9,
	NewEnumerator7                           = 10,
	NewEnumerator8                           = 11,
	NewEnumerator9                           = 12,
	NewEnumerator10                          = 13,
	NewEnumerator11                          = 14,
	NewEnumerator12                          = 15,
	NewEnumerator18                          = 16,
	NewEnumerator14                          = 17,
	NewEnumerator16                          = 18,
	NewEnumerator17                          = 19,
	NewEnumerator19                          = 20,
	NewEnumerator23                          = 21,
	BPE_MAX                                  = 22,
};

}

