#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Lingyang_AirAttackPro

#include "Basic.hpp"

#include "GA_Lingyang_AirAttackPro_classes.hpp"
#include "GA_Lingyang_AirAttackPro_parameters.hpp"


namespace SDK
{

// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.ExecuteUbergraph_GA_Lingyang_AirAttackPro
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Lingyang_AirAttackPro_C::ExecuteUbergraph_GA_Lingyang_AirAttackPro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "ExecuteUbergraph_GA_Lingyang_AirAttackPro");

	Params::GA_Lingyang_AirAttackPro_C_ExecuteUbergraph_GA_Lingyang_AirAttackPro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Lingyang_AirAttackPro_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "K2_OnEndAbility");

	Params::GA_Lingyang_AirAttackPro_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCompleted_5D118C384AE61F1C80292E81B244EC97
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCompleted_5D118C384AE61F1C80292E81B244EC97()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCompleted_5D118C384AE61F1C80292E81B244EC97");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnBlendOut_5D118C384AE61F1C80292E81B244EC97
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnBlendOut_5D118C384AE61F1C80292E81B244EC97()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnBlendOut_5D118C384AE61F1C80292E81B244EC97");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnInterrupted_5D118C384AE61F1C80292E81B244EC97
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnInterrupted_5D118C384AE61F1C80292E81B244EC97()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnInterrupted_5D118C384AE61F1C80292E81B244EC97");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCancelled_5D118C384AE61F1C80292E81B244EC97
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCancelled_5D118C384AE61F1C80292E81B244EC97()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCancelled_5D118C384AE61F1C80292E81B244EC97");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnTick_5D118C384AE61F1C80292E81B244EC97
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnTick_5D118C384AE61F1C80292E81B244EC97()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnTick_5D118C384AE61F1C80292E81B244EC97");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCompleted_5D118C384AE61F1C80292E81168308B2
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCompleted_5D118C384AE61F1C80292E81168308B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCompleted_5D118C384AE61F1C80292E81168308B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnBlendOut_5D118C384AE61F1C80292E81168308B2
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnBlendOut_5D118C384AE61F1C80292E81168308B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnBlendOut_5D118C384AE61F1C80292E81168308B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnInterrupted_5D118C384AE61F1C80292E81168308B2
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnInterrupted_5D118C384AE61F1C80292E81168308B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnInterrupted_5D118C384AE61F1C80292E81168308B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCancelled_5D118C384AE61F1C80292E81168308B2
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCancelled_5D118C384AE61F1C80292E81168308B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCancelled_5D118C384AE61F1C80292E81168308B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnTick_5D118C384AE61F1C80292E81168308B2
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnTick_5D118C384AE61F1C80292E81168308B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnTick_5D118C384AE61F1C80292E81168308B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCompleted_5D118C384AE61F1C80292E81CCE79371
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCompleted_5D118C384AE61F1C80292E81CCE79371()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCompleted_5D118C384AE61F1C80292E81CCE79371");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnBlendOut_5D118C384AE61F1C80292E81CCE79371
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnBlendOut_5D118C384AE61F1C80292E81CCE79371()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnBlendOut_5D118C384AE61F1C80292E81CCE79371");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnInterrupted_5D118C384AE61F1C80292E81CCE79371
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnInterrupted_5D118C384AE61F1C80292E81CCE79371()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnInterrupted_5D118C384AE61F1C80292E81CCE79371");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCancelled_5D118C384AE61F1C80292E81CCE79371
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCancelled_5D118C384AE61F1C80292E81CCE79371()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCancelled_5D118C384AE61F1C80292E81CCE79371");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnTick_5D118C384AE61F1C80292E81CCE79371
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnTick_5D118C384AE61F1C80292E81CCE79371()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnTick_5D118C384AE61F1C80292E81CCE79371");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCompleted_5D118C384AE61F1C80292E811C4A0789
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCompleted_5D118C384AE61F1C80292E811C4A0789()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCompleted_5D118C384AE61F1C80292E811C4A0789");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnBlendOut_5D118C384AE61F1C80292E811C4A0789
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnBlendOut_5D118C384AE61F1C80292E811C4A0789()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnBlendOut_5D118C384AE61F1C80292E811C4A0789");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnInterrupted_5D118C384AE61F1C80292E811C4A0789
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnInterrupted_5D118C384AE61F1C80292E811C4A0789()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnInterrupted_5D118C384AE61F1C80292E811C4A0789");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnCancelled_5D118C384AE61F1C80292E811C4A0789
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnCancelled_5D118C384AE61F1C80292E811C4A0789()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnCancelled_5D118C384AE61F1C80292E811C4A0789");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Lingyang_AirAttackPro.GA_Lingyang_AirAttackPro_C.OnTick_5D118C384AE61F1C80292E811C4A0789
// (BlueprintCallable, BlueprintEvent)

void UGA_Lingyang_AirAttackPro_C::OnTick_5D118C384AE61F1C80292E811C4A0789()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Lingyang_AirAttackPro_C", "OnTick_5D118C384AE61F1C80292E811C4A0789");

	UObject::ProcessEvent(Func, nullptr);
}

}

