#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ME1BinlangMd00601_Attack01_4

#include "Basic.hpp"

#include "GA_ME1BinlangMd00601_Attack01_4_classes.hpp"
#include "GA_ME1BinlangMd00601_Attack01_4_parameters.hpp"


namespace SDK
{

// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.ExecuteUbergraph_GA_ME1BinlangMd00601_Attack01_4
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_ME1BinlangMd00601_Attack01_4_C::ExecuteUbergraph_GA_ME1BinlangMd00601_Attack01_4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "ExecuteUbergraph_GA_ME1BinlangMd00601_Attack01_4");

	Params::GA_ME1BinlangMd00601_Attack01_4_C_ExecuteUbergraph_GA_ME1BinlangMd00601_Attack01_4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_ME1BinlangMd00601_Attack01_4_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "K2_OnEndAbility");

	Params::GA_ME1BinlangMd00601_Attack01_4_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.OnCompleted_5D118C384AE61F1C80292E814D666CA5
// (BlueprintCallable, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::OnCompleted_5D118C384AE61F1C80292E814D666CA5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "OnCompleted_5D118C384AE61F1C80292E814D666CA5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.OnBlendOut_5D118C384AE61F1C80292E814D666CA5
// (BlueprintCallable, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::OnBlendOut_5D118C384AE61F1C80292E814D666CA5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "OnBlendOut_5D118C384AE61F1C80292E814D666CA5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.OnInterrupted_5D118C384AE61F1C80292E814D666CA5
// (BlueprintCallable, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::OnInterrupted_5D118C384AE61F1C80292E814D666CA5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "OnInterrupted_5D118C384AE61F1C80292E814D666CA5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.OnCancelled_5D118C384AE61F1C80292E814D666CA5
// (BlueprintCallable, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::OnCancelled_5D118C384AE61F1C80292E814D666CA5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "OnCancelled_5D118C384AE61F1C80292E814D666CA5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.OnTick_5D118C384AE61F1C80292E814D666CA5
// (BlueprintCallable, BlueprintEvent)

void UGA_ME1BinlangMd00601_Attack01_4_C::OnTick_5D118C384AE61F1C80292E814D666CA5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "OnTick_5D118C384AE61F1C80292E814D666CA5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME1BinlangMd00601_Attack01_4.GA_ME1BinlangMd00601_Attack01_4_C.EventReceived_18B59F5945020DB23C42FD88D9EF6DCA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_ME1BinlangMd00601_Attack01_4_C::EventReceived_18B59F5945020DB23C42FD88D9EF6DCA(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME1BinlangMd00601_Attack01_4_C", "EventReceived_18B59F5945020DB23C42FD88D9EF6DCA");

	Params::GA_ME1BinlangMd00601_Attack01_4_C_EventReceived_18B59F5945020DB23C42FD88D9EF6DCA Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}

}

