#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ME1BinlangMd00601_Attack01_8

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Monster_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ME1BinlangMd00601_Attack01_8.GA_ME1BinlangMd00601_Attack01_8_C
// 0x0008 (0x0548 - 0x0540)
class UGA_ME1BinlangMd00601_Attack01_8_C final : public UGA_Monster_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_ME1BinlangMd00601_Attack01_8_C;  // 0x0540(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_ME1BinlangMd00601_Attack01_8(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E8183C54A75();
	void OnBlendOut_5D118C384AE61F1C80292E8183C54A75();
	void OnInterrupted_5D118C384AE61F1C80292E8183C54A75();
	void OnCancelled_5D118C384AE61F1C80292E8183C54A75();
	void OnTick_5D118C384AE61F1C80292E8183C54A75();
	void EventReceived_18B59F5945020DB23C42FD88CDA22885(const struct FGameplayEventData& Payload);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_ME1BinlangMd00601_Attack01_8_C">();
	}
	static class UGA_ME1BinlangMd00601_Attack01_8_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ME1BinlangMd00601_Attack01_8_C>();
	}
};
static_assert(alignof(UGA_ME1BinlangMd00601_Attack01_8_C) == 0x000008, "Wrong alignment on UGA_ME1BinlangMd00601_Attack01_8_C");
static_assert(sizeof(UGA_ME1BinlangMd00601_Attack01_8_C) == 0x000548, "Wrong size on UGA_ME1BinlangMd00601_Attack01_8_C");
static_assert(offsetof(UGA_ME1BinlangMd00601_Attack01_8_C, UberGraphFrame_GA_ME1BinlangMd00601_Attack01_8_C) == 0x000540, "Member 'UGA_ME1BinlangMd00601_Attack01_8_C::UberGraphFrame_GA_ME1BinlangMd00601_Attack01_8_C' has a wrong offset!");

}

