#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STrailLandPair

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct STrailLandPair.STrailLandPair
// 0x0020 (0x0020 - 0x0000)
struct FSTrailLandPair final
{
public:
	TArray<int32>                                 Index_5_F5082EC14F0DB5644C8813B34C75F939;          // 0x0000(0x0010)(Edit, BlueprintVisible)
	TArray<bool>                                  Show_6_83617CA34016D2DF24939D87244C6AE1;           // 0x0010(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FSTrailLandPair) == 0x000008, "Wrong alignment on FSTrailLandPair");
static_assert(sizeof(FSTrailLandPair) == 0x000020, "Wrong size on FSTrailLandPair");
static_assert(offsetof(FSTrailLandPair, Index_5_F5082EC14F0DB5644C8813B34C75F939) == 0x000000, "Member 'FSTrailLandPair::Index_5_F5082EC14F0DB5644C8813B34C75F939' has a wrong offset!");
static_assert(offsetof(FSTrailLandPair, Show_6_83617CA34016D2DF24939D87244C6AE1) == 0x000010, "Member 'FSTrailLandPair::Show_6_83617CA34016D2DF24939D87244C6AE1' has a wrong offset!");

}

